name: BudLords
version: '${project.version}'
main: com.budlords.BudLords
api-version: '1.20'
description: A weed farming RPG + black market economy system for Minecraft - v2.0.1 Bug Fix & Content Update
author: BudLords Team

commands:
  bal:
    description: Check your balance
    usage: /<command>
    permission: budlords.balance
  addmoney:
    description: Add money to a player
    usage: /<command> <player> <amount>
    permission: budlords.admin
  pay:
    description: Pay another player
    usage: /<command> <player> <amount>
    permission: budlords.pay
  straincreator:
    description: Open the strain creator GUI
    usage: /<command>
    permission: budlords.admin
  spawnmarket:
    description: Spawn Market Joe NPC
    usage: /<command>
    permission: budlords.admin
  spawnblackmarket:
    description: Spawn BlackMarket Joe NPC
    usage: /<command>
    permission: budlords.admin
  package:
    description: Package weed buds (Operator only)
    usage: /<command> <amount>
    permission: budlords.admin
  budlords:
    description: Main BudLords command
    usage: /<command>
    permission: budlords.use
  stats:
    description: View your BudLords statistics
    usage: /<command>
    permission: budlords.use
  prestige:
    description: Open the prestige menu
    usage: /<command>
    permission: budlords.use
  challenges:
    description: View daily and weekly challenges
    usage: /<command>
    permission: budlords.use
  crossbreed:
    description: Open the crossbreeding lab
    usage: /<command>
    permission: budlords.use
  leaderboard:
    description: View server leaderboards
    usage: /<command> [category]
    aliases: [lb, top]
    permission: budlords.use
  # v2.0.0 New Commands
  season:
    description: View current season and bonuses
    usage: /<command> [info|set]
    permission: budlords.use
  achievements:
    description: View your achievements
    usage: /<command> [category]
    aliases: [achieve, ach]
    permission: budlords.use
  skills:
    description: View and manage your skill tree
    usage: /<command> [tree]
    aliases: [skill, skilltree]
    permission: budlords.use
  collection:
    description: View your strain collection book
    usage: /<command> [page]
    aliases: [book, strainbook]
    permission: budlords.use
  # Admin Debug Command
  debug:
    description: Admin debug tools for testing BudLords
    usage: /<command> [toggle|plants|strains|player|effects|economy|entity|growplant|giveeffect|testmutation|reload|save|config|clear]
    aliases: [bldebug, budlordsdebug]
    permission: budlords.admin

permissions:
  budlords.use:
    description: Basic BudLords usage
    default: true
  budlords.balance:
    description: Check balance
    default: true
  budlords.pay:
    description: Pay other players
    default: true
  budlords.package:
    description: Package weed
    default: true
  budlords.admin:
    description: Admin commands
    default: op
